apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: qa-poc-ns
spec:
  type: NodePort
  selector:
    app: hello-api
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
